version: '3.3'

services:
  mysql:
    image: mysql:8.4
    container_name: linkcut-mysql-8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: linkcut
      MYSQL_USER: linkcut
      MYSQL_PASSWORD: linkcut123
    ports:
      - "3306:3306"
    volumes:
      - /XiyueTsuki-Star-LinkCut-Demo/MySQL-8.4/data:/var/lib/mysql
      - /XiyueTsuki-Star-LinkCut-Demo/MySQL-8.4/conf:/etc/mysql/conf.d
      - /XiyueTsuki-Star-LinkCut-Demo/MySQL-8.4/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - linkcut

  redis:
    image: redis:8.2
    container_name: linkcut-redis-8.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /XiyueTsuki-Star-LinkCut-Demo/Redis-8.2/data:/data
      - /XiyueTsuki-Star-LinkCut-Demo/Redis-8.2/conf:/usr/local/etc/redis
    networks:
      - linkcut

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.0
    container_name: linkcut-rmq-namesrv-5.3.0
    restart: unless-stopped
    user: root
    ports:
      - "9876:9876"
    environment:
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn128m"
    command: sh mqnamesrv
    volumes:
      - /XiyueTsuki-Star-LinkCut-Demo/RocketMQ-5.3.0/namesrv/logs:/home/rocketmq/logs
    networks:
      - linkcut

  rocketmq-broker:
    image: apache/rocketmq:5.3.0
    container_name: linkcut-rmq-broker-5.3.0
    restart: unless-stopped
    user: root
    ports:
      - "10911:10911"
    environment:
      NAMESRV_ADDR: rocketmq-namesrv:9876
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn256m"
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.0/conf/broker.conf
    volumes:
      - /XiyueTsuki-Star-LinkCut-Demo/RocketMQ-5.3.0/broker/logs:/home/rocketmq/logs
      - /XiyueTsuki-Star-LinkCut-Demo/RocketMQ-5.3.0/broker/store:/home/rocketmq/store
      - /XiyueTsuki-Star-LinkCut-Demo/RocketMQ-5.3.0/broker.conf:/home/rocketmq/rocketmq-5.3.0/conf/broker.conf
    depends_on:
      - rocketmq-namesrv
    networks:
      - linkcut

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:2.1.0
    container_name: linkcut-rmq-dashboard
    restart: unless-stopped
    ports:
      - "4003:8082"
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rocketmq-namesrv
    networks:
      - linkcut

networks:
  linkcut:
    driver: bridge