# RocketMQ Broker 配置
brokerClusterName = LinkCutCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 自动创建 Topic
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true

# 监听端口
listenPort = 10911

# 对外宣告的地址（虚拟机IP，否则客户端拿到的是容器内部IP）
brokerIP1 = 192.168.100.128

# 存储路径
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog